name: clone
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  http: ^1.5.0
  dio: ^5.9.0
  internet_connection_checker_plus: ^2.7.2
  shared_preferences: ^2.5.3
  get_it: ^8.2.0
  logger: ^2.6.1
  go_router: ^16.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
 

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/dashboard/
    - assets/dashboard/place_order.png
    - assets/33.png
    - assets/logo1.png
